language: php
dist: xenial

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: vendor/bin/phpunit
